### PR TITLE
check for errors when loading config file

### LINKED ISSUE #2: jiran config crashes when ~/.jira/config.json not found
Hi,
I've just installed jiran and when I run `jiran config` for the first time it crashes with the error trace:

```
fs.js:438
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/Users/xxx/.jira/config.json'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at Config.detail (/xxx/node_modules/jiran/lib/cli/config.js:37:27)
    at Object.<anonymous> (/xxx/node_modules/jiran/lib/jiran.js:12:54)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

The directory `.jira` was there, only file was missing. The other thing - when I created a file with `touch ~/.jira/config.json` it failed saying 

```
undefined:0

^
SyntaxError: Unexpected end of input
```

### PR DESCRIPTION
**Pull request by mike182uk**
fixes #2

### CODE REVIEW

**Comment by marek-pietrzak-tg** [comment]
Thanks for the fix @mike182uk, but I think it doesn't resolve the whole problem. I still get an error, this time nicer though. 
I would expect a config file being created when I run `jiran config` for the first time and the file doesn't exist yet.

**Comment by danielkmariam** [comment]
I have resolved the issue by separating the commands
1. If config file does not exist, users will be prompted wit message and the command to run
2. If config file already exists the users will see all options

Please check my changes and let me know what you think

**Comment by danielkmariam** [comment]
Am closing this as it is already fixed, thanks guys

**Comment by mike182uk** [comment]
:+1:

**Pull request closed without merging**
